services:
  web:
    build: .
    volumes:
      - ./media:/minigame/media
      - ./staticfiles:/minigame/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/var/www/staticfiles:ro
      - ./media:/var/www/media:ro
    depends_on:
      - web
    restart: unless-stopped

  db:
    image: postgres:17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata: